CREATE DATABASE BANCOSOLAR;

DROP TABLE IF EXISTS TRANSFERENCIAS;
DROP TABLE IF EXISTS USUARIOS;


CREATE TABLE USUARIOS (
id SERIAL PRIMARY KEY,
nombre VARCHAR(50),
balance FLOAT CHECK (balance >= 0)
);


CREATE TABLE TRANSFERENCIAS (
id SERIAL PRIMARY KEY,
emisor INT,
receptor INT,
monto FLOAT,
fecha TIMESTAMP,
FOREIGN KEY (emisor) REFERENCES USUARIOS(id) ON DELETE CASCADE,
FOREIGN KEY (receptor) REFERENCES USUARIOS(id) ON DELETE CASCADE
);

INSERT INTO USUARIOS (nombre, balance) VALUES 
('Pedro Rojas', 100000),
('Daniela Peralta', 250000), 
('Borja Alfaro', 150000);